### PR TITLE
Support digits in atoms

### PR DESCRIPTION
**Pull request by lgalarra**
I have modified the regex that parses terms in atoms to support digits.

### CODE REVIEW

**Comment by lajus** [comment]
Hi,

I already pushed the change long time ago (adding \w instead of \d) cf issue #21.

Jonathan

**Comment by lgalarra** [comment]
Hi Jonathan,

I do not understand, I thought \w does not match digits. Without those changes AMIE cannot parse the following rule mined from Freebase (because of the digits in the predicate):

?a  /location/statistical_region/rent50_1./measurement_unit/dated_money_value/currency  ?b   => ?a  /location/statistical_region/rent50_2./measurement_unit/dated_money_value/currency

Cheers,
Luis

**Comment by lajus** [comment]
Hi,

It does: https://www.w3schools.com/jsref/jsref_regexp_wordchar.asp

If you pull the master branch there should be no problem parsing those predicates.

Jonathan

**Comment by lgalarra** [comment]
I see! I was confused by the \p{L}, which allows us to match non-ascii letters. I will then get the code from the master branch. Thanks and sorry for the false alarm.

**Pull request closed without merging**
